version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: lin-postgres
    environment:
      POSTGRES_DB: secrets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lin-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 15

  backend:
    build: .
    container_name: lin-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: secrets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - lin-net

volumes:
  pgdata:

networks:
  lin-net:
    driver: bridge
